### ISSUE TITLE
Gamma value might be to high 

### ISSUE THREAD

**Issue by jennytigerholm** [TaberBuus/Cand.polyt-1.-semester#1]
As I Understand your gamma value is set to 0.5 (paramsGen = [0, 1, .5, .02]).
When I plot the psychmetric function It looks like this:
(x=-1:0.001:1; plot(x,PAL_Gumbel([0, 1, .5, .02], x ))

[student_hab_pf.pdf](https://github.com/TaberBuus/Cand.polyt-1.-semester/files/5407325/student_hab_pf.pdf)

A gamma of 0.5, means that 50% of the time the subject report that they feel the stimulation by mistake.
If I am understanding this correctly then gamma is definitely too high and should be around 0.05.
If you change the gamma, this should lead to much better convergence and is more alike to the experimental setting we are using. This is only a suggestion and I might have misunderstood how your gamma value is defined.

**Comment by TaberBuus** [comment]
the gamma value has now been change, and method work much better :-)
